### ISSUE TITLE
Disable scrolling up

### ISSUE THREAD

**Issue by acerbastimur** [35d/react-native-half-modal#4]
Can you bring a feature to disable scrolling up ?

**Comment by 35d** [comment]
@acerbastimur 

Thank you for creating this Issue.
Does "disable scrolling up" mean a movement that pulls the modal up?

**Comment by acerbastimur** [comment]
Yes. That was what I meant

**Comment by 35d** [comment]
Thank you.

I will add to the development plan and want to release by October.

**Comment by 35d** [comment]
Hi @acerbastimur

I added disable scrolling props up function in v0.2.4.
Would you like to check this function?

Example 
 ```
<SemiModal isVisible={this.state.isVisible} onModalClose={this.modalClose} style={styles.SemiModal} disableTopScroll>
```

**Comment by acerbastimur** [comment]
Thank you !

**Comment by acerbastimur** [comment]
It throws an error on swiping up

http://prntscr.com/p0fgv9

**Comment by 35d** [comment]
:memo: v0.2.5 released.
